#!/bin/sh
path=$(pwd)

# Home directory
ln -sf $path/.Xresources $HOME/.Xresources
ln -sf $path/.xinitrc $HOME/.xinitrc
ln -sf $path/.Xmodmap $HOME/.Xmodmap
ln -sf $path/.zprofile $HOME/.zprofile
ln -sf $path/.zshrc $HOME/.zshrc

# Config directory
[ ! -d $HOME/.config ] && mkdir $HOME/.config
[ ! -d $HOME/.local/bin ] && mkdir $HOME/.local/bin

if [ -L $HOME/.config/cava ]; then
  rm $HOME/.config/cava
fi
ln -sf $path/.config/cava $HOME/.config/cava

if [ -L $HOME/.config/dunst ]; then
  rm $HOME/.config/dunst
fi
ln -sf $path/.config/dunst $HOME/.config/dunst

if [ -L $HOME/.config/mpv ]; then
  rm $HOME/.config/mpv
fi
ln -sf $path/.config/mpv $HOME/.config/mpv

if [ -L $HOME/.config/neofetch ]; then
  rm $HOME/.config/neofetch
fi
ln -sf $path/.config/neofetch $HOME/.config/neofetch

if [ -L $HOME/.config/picom ]; then
  rm $HOME/.config/picom
fi
ln -sf $path/.config/picom $HOME/.config/picom

if [ -L $HOME/.config/ranger ]; then
  rm $HOME/.config/ranger
fi
ln -sf $path/.config/ranger $HOME/.config/ranger

if [ -L $HOME/.config/zathura ]; then
  rm $HOME/.config/zathura
fi
ln -sf $path/.config/zathura $HOME/.config/zathura

if [ -L $HOME/.config/qutebrowser ]; then
  rm $HOME/.config/qutebrowser
fi
ln -sf $path/.config/qutebrowser $HOME/.config/qutebrowser

if [ -L $HOME/.config/cmus ]; then
  rm $HOME/.config/cmus
fi
ln -sf $path/.config/cmus $HOME/.config/cmus

if [ -L $HOME/.config/suckless ]; then
  rm $HOME/.config/suckless
fi
ln -sf $path/.config/suckless $HOME/.config/suckless

if [ -L $HOME/.config/zsh ]; then
  rm $HOME/.config/zsh
fi
ln -sf $path/.config/zsh $HOME/.config/zsh

if [ -L $HOME/.emacs.d ]; then
  rm $HOME/.emacs.d
fi
ln -sf $path/.emacs.d/ $HOME/.emacs.d


ln -sf $path/.local/bin/cmus-notify $HOME/.local/bin
ln -sf $path/.local/bin/dwall $HOME/.local/bin
ln -sf $path/.local/bin/dfiles $HOME/.local/bin
ln -sf $path/.local/bin/emoji $HOME/.local/bin
ln -sf $path/.local/bin/screenshot $HOME/.local/bin
ln -sf $path/.local/bin/togglemute $HOME/.local/bin
