#!/bin/bash

path=$(pwd)

clear
echo "    ___    __________  _   ___ _____    ____  ____  __________________    ___________"
echo "   /   |  / ____/ __ \/ | / ( ) ___/   / __ \/ __ \/_  __/ ____/  _/ /   / ____/ ___/"
echo "  / /| | / __/ / / / /  |/ /|/\__ \   / / / / / / / / / / /_   / // /   / __/  \__ \        https://github.com/seeingangelz"
echo " / ___ |/ /___/ /_/ / /|  /  ___/ /  / /_/ / /_/ / / / / __/ _/ // /___/ /___ ___/ /                     by Aeon"
echo "/_/  |_/_____/\____/_/ |_/  /____/  /_____/\____/ /_/ /_/   /___/_____/_____//____/"
echo ""
echo ""
echo "Install programs and dependencies? (y/n)"
read answer
sleep 1 && clear

case $answer in
  "y")
    echo "Installing dependencies..."
    sudo pacman -S arandr arc-gtk-theme cmus dbus dunst emacs feh ffmpeg ffmpegthumbnailer firefox flameshot fzf git gnu-free-fonts go htop imagemagick lxappearance mpv neofetch neovim noto-fonts noto-fonts-cjk noto-fonts-emoji numlockx obs-studio openssh perl pulseaudio pulsemixer python-pip python-pywal qalculate-gtk qt5ct qutebrowser ranger syncthing sxiv telegram-desktop tmux tree ttf-jetbrains-mono ttf-nerd-fonts-symbols-common ttf-nerd-fonts-symbols-2048-em-mono ueberzug redshift unzip vim webkit2gtk xclip yt-dlp zathura zathura-pdf-mupdf zip xorg-server xorg-xinit libx11 libxinerama libxft base base-devel
    sleep 1 && clear
    ;;
  "n")
    echo "Skipping..."
    sleep 1 && clear
    ;;
  *)
    echo "Invalid answer, skipping..."
    sleep 1 && clear
    ;;
esac

echo "Installing AUR programs, already have yay installed? (y/n)"
read answer
sleep 1 && clear

case $answer in
  "y")
    echo "Installing AUR programs..."
    yay -S cava devour picom-jonaburg-git cmatrix-git qt5-styleplugins checkupdates-aur perl-checkupdates-aur
    sleep 1 && clear
    ;;
  "n")
    echo "Installing yay..."
    git clone https://aur.archlinux.org/yay.git ~/.yay
    cd ~/.yay
    makepkg -si 
    sudo rm -rf ~/.yay
    sleep 1 && clear
    
    echo "Installing AUR programs..."
    yay -S cava devour picom-jonaburg-git cmatrix-git qt5-styleplugins webtorrent-cli
    sleep 1 && clear
    ;;
  *)
    echo "Invalid answer, skipping..."
    sleep 1 && clear
    ;;
esac

echo "Is this installation on a laptop? (y/n)"
read answer
sleep 1 && clear

case $answer in
  "y")
    echo "Installing dependencies..."
    sudo pacman -S acpi acpilight
    sleep 1 && clear
    ;;
  "n")
    echo "Skipping..."
    sleep 1 && clear
    ;;
  *)
    echo "Invalid answer, skipping..."
    sleep 1 && clear
    ;;
esac

echo "Alredy have Oh-My-Zsh installed? (y/n)"
read answer
sleep 1 && clear

case $answer in
  "y")
    if [ -L $HOME/.config/zsh ]; then
    rm $HOME/.config/zsh
    fi
    ln -sfv $path/.config/zsh $HOME/.config/zsh 

    if [ -L $HOME/.zshrc ]; then
    rm $HOME/.zshrc
    fi
    ln -sfv $path/.zshrc $HOME/.zshrc
    sleep 1 && clear
    ;;
  "n")
    echo "Installing..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    if [ -L $HOME/.config/zsh ]; then
    rm $HOME/.config/zsh
    fi
    ln -sfv $path/.config/zsh $HOME/.config/zsh 

    if [ -L $HOME/.zshrc ]; then
    rm $HOME/.zshrc
    fi
    ln -sfv $path/.zshrc $HOME/.zshrc
    sleep 1 && clear
    ;;
  *)
    echo "Invalid answer, skipping..."
    sleep 1 && clear
    ;;
esac


echo "Creating symbolic links..."
echo ""
ln -sfv $path/.Xresources $HOME/.Xresources
ln -sfv $path/.xinitrc $HOME/.xinitrc
ln -sfv $path/.Xmodmap $HOME/.Xmodmap
ln -sfv $path/.zprofile $HOME/.zprofile

[ ! -d $HOME/.config ] && mkdir $HOME/.config
[ ! -d $HOME/.local ] && mkdir $HOME/.local
[ ! -d $HOME/.local/bin ] && mkdir $HOME/.local/bin

if [ -L $HOME/.config/cava ]; then
  rm -rf $HOME/.config/cava
fi
ln -sfv $path/.config/cava $HOME/.config/cava

if [ -L $HOME/.config/redshift ]; then
  rm -rf $HOME/.config/redshift
fi
ln -sfv $path/.config/redshift $HOME/.config/redshift

if [ -L $HOME/.config/dunst ]; then
  rm -rf $HOME/.config/dunst
fi
ln -sfv $path/.config/dunst $HOME/.config/dunst

if [ -L $HOME/.config/mpv ]; then
  rm -rf $HOME/.config/mpv
fi
ln -sfv $path/.config/mpv $HOME/.config/mpv

if [ -L $HOME/.config/neofetch ]; then
  rm -rf $HOME/.config/neofetch
fi
ln -sfv $path/.config/neofetch $HOME/.config/neofetch

if [ -L $HOME/.config/sxiv ]; then
  rm -rf $HOME/.config/sxiv
fi
ln -sfv $path/.config/sxiv $HOME/.config/sxiv

if [ -L $HOME/.config/wal ]; then
  rm -rf $HOME/.config/wal
fi
ln -sfv $path/.config/wal $HOME/.config/wal
ln -sfv $HOME/.cache/wal/dunstrc $HOME/.config/dunst/dunstrc

if [ -L $HOME/.config/picom ]; then
  rm -rf $HOME/.config/picom
fi
ln -sfv $path/.config/picom $HOME/.config/picom

if [ -L $HOME/.config/ranger ]; then
  rm -rf $HOME/.config/ranger
fi
ln -sfv $path/.config/ranger $HOME/.config/ranger

if [ -L $HOME/.config/zathura ]; then
  rm -rf $HOME/.config/zathura
fi
ln -sfv $path/.config/zathura $HOME/.config/zathura

if [ -L $HOME/.config/qutebrowser ]; then
  rm -rf $HOME/.config/qutebrowser
fi
ln -sfv $path/.config/qutebrowser $HOME/.config/qutebrowser

if [ -L $HOME/.config/cmus ]; then
  rm -rf $HOME/.config/cmus
fi
ln -sfv $path/.config/cmus $HOME/.config/cmus

if [ -L $HOME/.config/suckless ]; then
  rm -rf $HOME/.config/suckless
fi
ln -sfv $path/.config/suckless $HOME/.config/suckless

if [ -L $HOME/.config/nvim ]; then
  rm -rf $HOME/.config/nvim
fi
ln -sfv $path/.config/nvim $HOME/.config/nvim

if [ -L $HOME/.emacs.d ]; then
  rm -rf $HOME/.emacs.d
fi
ln -sfv $path/.emacs.d/ $HOME/.emacs.d

ln -sfv $path/.local/bin/cmus-notify $HOME/.local/bin
ln -sfv $path/.local/bin/dwall $HOME/.local/bin
ln -sfv $path/.local/bin/wg $HOME/.local/bin
ln -sfv $path/.local/bin/dfiles $HOME/.local/bin
ln -sfv $path/.local/bin/dstreaming $HOME/.local/bin
ln -sfv $path/.local/bin/emoji $HOME/.local/bin
ln -sfv $path/.local/bin/screenshot $HOME/.local/bin
ln -sfv $path/.local/bin/togglemute $HOME/.local/bin
ln -sfv $path/.local/bin/nightmode $HOME/.local/bin
ln -sfv $path/.local/bin/dwifi $HOME/.local/bin
sleep 1 && clear

echo "Installing suckless programs..."
cd $path/.config/suckless/dwm && sudo make clean install && mv -f config.h config.def.h
cd $path/.config/suckless/st && sudo make clean install && mv -f config.h config.def.h
cd $path/.config/suckless/dmenu && sudo make clean install && mv -f config.h config.def.h
cd $path/.config/suckless/slock && sudo make clean install && mv -f config.h config.def.h

chmod x $path/.local/bin
sleep 1 && clear

echo "Changing default shell..."
chsh -s /usr/bin/zsh
sleep 1 && clear

echo "All done!"
echo "Please log out and log back in for the changes to take effect."
