#!/bin/sh

is_process_running() {
  pgrep -x "$1" >/dev/null
}

if is_process_running "dwm"; then
  window_manager="dwm"
elif is_process_running "awesome"; then
  window_manager="awesome"
else
  window_manager="unknown"
fi

while read file
do
  case "$1" in
  "w")
    wal -i "$file"
    sed -i ~/.Xresources -re '1,1000d'
    cat ~/.cache/wal/colors.Xresources >> ~/.Xresources
    oomox-cli /opt/oomox/scripted_colors/xresources/xresources-reverse
    betterlockscreen -u "$file"
    wal-telegram -t
    pywalfox update
    killall dunst && dunst &

    if [ "$window_manager" = "dwm" ]; then
      killall dwm
      killall dwmblocks
      dwmblocks &
    elif [ "$window_manager" = "awesome" ]; then
      pkill -HUP awesome
      picom --experimental-backends
    fi

    pkill sxiv
    notify-send "Enjoy your new colorscheme!"
    ;;

  "y")
    xclip -selection clipboard "$file" -t image/png &&
    notify-send "$file copied to clipboard!"
  esac
done
